# Generated by Django 2.0.7 on 2018-10-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inverntory',
            new_name='Inventory',
        ),
    ]
